import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | CommerceX',
  description: 'Terms and conditions governing the use of the CommerceX platform and services.',
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen pt-24 pb-32 bg-background">
      <section className="container mx-auto px-4 md:px-6 max-w-3xl">
        <div className="mb-12">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: October 24, 2024</p>
        </div>
        
        <div className="prose prose-neutral dark:prose-invert max-w-none text-muted-foreground prose-headings:text-foreground">
          <h2>1. Introduction</h2>
          <p>
            Welcome to CommerceX. By accessing our platform, you agree to these Terms of Service. Please read them carefully.
          </p>
          
          <h2>2. Service Provision</h2>
          <p>
            CommerceX provides a multi-tenant ecommerce software-as-a-service (SaaS) platform. We are responsible for maintaining the uptime, security, and performance of the core infrastructure. You are responsible for your store's content, legal compliance, and customer interactions.
          </p>
          
          <h2>3. Acceptable Use</h2>
          <p>
            You agree not to use the CommerceX platform to sell illegal goods, distribute malware, or engage in fraudulent activities. We reserve the right to suspend or terminate accounts violating these terms without prior notice.
          </p>

          <h2>4. Data Ownership</h2>
          <p>
            You retain full ownership of all customer data, product catalogs, and transaction records generated by your storefronts. CommerceX claims no ownership over your intellectual property.
          </p>
        </div>
      </section>
    </div>
  );
}
