require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const CONTINENTS = [
  { code: 'AF', name: 'Africa', slug: 'africa' },
  { code: 'AN', name: 'Antarctica', slug: 'antarctica' },
  { code: 'AS', name: 'Asia', slug: 'asia' },
  { code: 'EU', name: 'Europe', slug: 'europe' },
  { code: 'NA', name: 'North America', slug: 'north-america' },
  { code: 'OC', name: 'Oceania', slug: 'oceania' },
  { code: 'SA', name: 'South America', slug: 'south-america' }
];


const CURRENCIES = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', slug: 'aed' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', slug: 'afn' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', slug: 'all' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', slug: 'amd' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', slug: 'ang' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', slug: 'aoa' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', slug: 'ars' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', slug: 'aud' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', slug: 'awg' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', slug: 'azn' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', slug: 'bam' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', slug: 'bbd' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', slug: 'bdt' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', slug: 'bgn' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', slug: 'bhd' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', slug: 'bif' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', slug: 'bmd' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', slug: 'bnd' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', slug: 'bob' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', slug: 'brl' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', slug: 'bsd' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', slug: 'btn' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', slug: 'bwp' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', slug: 'byn' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', slug: 'bzd' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', slug: 'cad' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', slug: 'cdf' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', slug: 'chf' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', slug: 'clp' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', slug: 'cny' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', slug: 'cop' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', slug: 'crc' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', slug: 'cup' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', slug: 'cve' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', slug: 'czk' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', slug: 'djf' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', slug: 'dkk' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', slug: 'dop' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'دج', slug: 'dzd' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', slug: 'egp' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', slug: 'ern' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', slug: 'etb' },
  { code: 'EUR', name: 'Euro', symbol: '€', slug: 'eur' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', slug: 'fjd' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', slug: 'fkp' },
  { code: 'GBP', name: 'British Pound', symbol: '£', slug: 'gbp' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', slug: 'gel' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', slug: 'ghs' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', slug: 'gip' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', slug: 'gmd' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', slug: 'gnf' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', slug: 'gtq' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', slug: 'gyd' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', slug: 'hkd' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', slug: 'hnl' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', slug: 'hrk' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', slug: 'htg' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', slug: 'huf' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', slug: 'idr' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', slug: 'ils' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', slug: 'inr' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', slug: 'iqd' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', slug: 'irr' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', slug: 'isk' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', slug: 'jmd' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', slug: 'jod' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', slug: 'jpy' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', slug: 'kes' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', slug: 'kgs' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', slug: 'khr' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', slug: 'kmf' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', slug: 'krw' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', slug: 'kwd' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI$', slug: 'kyd' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', slug: 'kzt' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', slug: 'lak' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', slug: 'lbp' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', slug: 'lkr' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', slug: 'lrd' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', slug: 'lsl' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', slug: 'lyd' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', slug: 'mad' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', slug: 'mdl' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', slug: 'mga' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', slug: 'mkd' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', slug: 'mmk' },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', slug: 'mnt' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', slug: 'mop' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', slug: 'mru' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', slug: 'mur' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', slug: 'mvr' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', slug: 'mwk' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', slug: 'mxn' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', slug: 'myr' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', slug: 'mzn' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', slug: 'nad' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', slug: 'ngn' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', slug: 'nio' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', slug: 'nok' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', slug: 'npr' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', slug: 'nzd' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', slug: 'omr' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', slug: 'pab' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', slug: 'pen' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', slug: 'pgk' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', slug: 'php' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', slug: 'pkr' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', slug: 'pln' },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', slug: 'pyg' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', slug: 'qar' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', slug: 'ron' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', slug: 'rsd' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', slug: 'rub' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', slug: 'rwf' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', slug: 'sar' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', slug: 'sbd' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', slug: 'scr' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', slug: 'sdg' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', slug: 'sek' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', slug: 'sgd' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', slug: 'shp' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', slug: 'sle' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', slug: 'sos' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', slug: 'srd' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', slug: 'ssp' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', slug: 'stn' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', slug: 'syp' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', slug: 'szl' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', slug: 'thb' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', slug: 'tjs' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', slug: 'tmt' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', slug: 'tnd' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', slug: 'top' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', slug: 'try' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', slug: 'ttd' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', slug: 'twd' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', slug: 'tzs' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', slug: 'uah' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', slug: 'ugx' },
  { code: 'USD', name: 'US Dollar', symbol: '$', slug: 'usd' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', slug: 'uyu' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', slug: 'uzs' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', slug: 'ves' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', slug: 'vnd' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', slug: 'vuv' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', slug: 'wst' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', slug: 'xaf' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', slug: 'xcd' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', slug: 'xof' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', slug: 'xpf' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', slug: 'yer' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', slug: 'zar' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', slug: 'zmw' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', slug: 'zwl' }
];


const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', slug: 'en' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', slug: 'hi' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', slug: 'bn' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', slug: 'te' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', slug: 'mr' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', slug: 'ta' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', slug: 'ur' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', slug: 'gu' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', slug: 'kn' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', slug: 'ml' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', slug: 'or' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', slug: 'pa' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', slug: 'as' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', slug: 'sa' },

  { code: 'es', name: 'Spanish', nativeName: 'Español', slug: 'es' },
  { code: 'fr', name: 'French', nativeName: 'Français', slug: 'fr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', slug: 'de' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', slug: 'it' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', slug: 'pt' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', slug: 'nl' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', slug: 'pl' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', slug: 'uk' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', slug: 'ru' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', slug: 'tr' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', slug: 'el' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', slug: 'cs' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', slug: 'sv' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', slug: 'da' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', slug: 'fi' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', slug: 'no' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', slug: 'hu' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', slug: 'ro' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', slug: 'bg' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', slug: 'sr' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', slug: 'sk' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', slug: 'hr' },

  { code: 'zh', name: 'Chinese', nativeName: '中文', slug: 'zh' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', slug: 'ja' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', slug: 'ko' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', slug: 'ar' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', slug: 'fa' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', slug: 'he' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', slug: 'th' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', slug: 'vi' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', slug: 'id' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', slug: 'ms' },
  { code: 'fil', name: 'Filipino', nativeName: 'Filipino', slug: 'fil' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', slug: 'sw' }
];


const COUNTRIES = [
  { iso2: 'AF', iso3: 'AFG', numericCode: '004', name: 'Afghanistan', slug: 'afghanistan', phoneCode: '+93', continentCode: 'AS' },
  { iso2: 'AL', iso3: 'ALB', numericCode: '008', name: 'Albania', slug: 'albania', phoneCode: '+355', continentCode: 'EU' },
  { iso2: 'DZ', iso3: 'DZA', numericCode: '012', name: 'Algeria', slug: 'algeria', phoneCode: '+213', continentCode: 'AF' },
  { iso2: 'AD', iso3: 'AND', numericCode: '020', name: 'Andorra', slug: 'andorra', phoneCode: '+376', continentCode: 'EU' },
  { iso2: 'AO', iso3: 'AGO', numericCode: '024', name: 'Angola', slug: 'angola', phoneCode: '+244', continentCode: 'AF' },
  { iso2: 'AG', iso3: 'ATG', numericCode: '028', name: 'Antigua and Barbuda', slug: 'antigua-and-barbuda', phoneCode: '+1-268', continentCode: 'NA' },
  { iso2: 'AR', iso3: 'ARG', numericCode: '032', name: 'Argentina', slug: 'argentina', phoneCode: '+54', continentCode: 'SA' },
  { iso2: 'AM', iso3: 'ARM', numericCode: '051', name: 'Armenia', slug: 'armenia', phoneCode: '+374', continentCode: 'AS' },
  { iso2: 'AU', iso3: 'AUS', numericCode: '036', name: 'Australia', slug: 'australia', phoneCode: '+61', continentCode: 'OC' },
  { iso2: 'AT', iso3: 'AUT', numericCode: '040', name: 'Austria', slug: 'austria', phoneCode: '+43', continentCode: 'EU' },
  { iso2: 'AZ', iso3: 'AZE', numericCode: '031', name: 'Azerbaijan', slug: 'azerbaijan', phoneCode: '+994', continentCode: 'AS' },

  { iso2: 'BS', iso3: 'BHS', numericCode: '044', name: 'Bahamas', slug: 'bahamas', phoneCode: '+1-242', continentCode: 'NA' },
  { iso2: 'BH', iso3: 'BHR', numericCode: '048', name: 'Bahrain', slug: 'bahrain', phoneCode: '+973', continentCode: 'AS' },
  { iso2: 'BD', iso3: 'BGD', numericCode: '050', name: 'Bangladesh', slug: 'bangladesh', phoneCode: '+880', continentCode: 'AS' },
  { iso2: 'BB', iso3: 'BRB', numericCode: '052', name: 'Barbados', slug: 'barbados', phoneCode: '+1-246', continentCode: 'NA' },
  { iso2: 'BY', iso3: 'BLR', numericCode: '112', name: 'Belarus', slug: 'belarus', phoneCode: '+375', continentCode: 'EU' },
  { iso2: 'BE', iso3: 'BEL', numericCode: '056', name: 'Belgium', slug: 'belgium', phoneCode: '+32', continentCode: 'EU' },
  { iso2: 'BZ', iso3: 'BLZ', numericCode: '084', name: 'Belize', slug: 'belize', phoneCode: '+501', continentCode: 'NA' },
  { iso2: 'BJ', iso3: 'BEN', numericCode: '204', name: 'Benin', slug: 'benin', phoneCode: '+229', continentCode: 'AF' },
  { iso2: 'BT', iso3: 'BTN', numericCode: '064', name: 'Bhutan', slug: 'bhutan', phoneCode: '+975', continentCode: 'AS' },
  { iso2: 'BO', iso3: 'BOL', numericCode: '068', name: 'Bolivia', slug: 'bolivia', phoneCode: '+591', continentCode: 'SA' },
  { iso2: 'BA', iso3: 'BIH', numericCode: '070', name: 'Bosnia and Herzegovina', slug: 'bosnia-and-herzegovina', phoneCode: '+387', continentCode: 'EU' },
  { iso2: 'BW', iso3: 'BWA', numericCode: '072', name: 'Botswana', slug: 'botswana', phoneCode: '+267', continentCode: 'AF' },
  { iso2: 'BR', iso3: 'BRA', numericCode: '076', name: 'Brazil', slug: 'brazil', phoneCode: '+55', continentCode: 'SA' },
  { iso2: 'BN', iso3: 'BRN', numericCode: '096', name: 'Brunei', slug: 'brunei', phoneCode: '+673', continentCode: 'AS' },
  { iso2: 'BG', iso3: 'BGR', numericCode: '100', name: 'Bulgaria', slug: 'bulgaria', phoneCode: '+359', continentCode: 'EU' },
  { iso2: 'BF', iso3: 'BFA', numericCode: '854', name: 'Burkina Faso', slug: 'burkina-faso', phoneCode: '+226', continentCode: 'AF' },
  { iso2: 'BI', iso3: 'BDI', numericCode: '108', name: 'Burundi', slug: 'burundi', phoneCode: '+257', continentCode: 'AF' },

  { iso2: 'KH', iso3: 'KHM', numericCode: '116', name: 'Cambodia', slug: 'cambodia', phoneCode: '+855', continentCode: 'AS' },
  { iso2: 'CM', iso3: 'CMR', numericCode: '120', name: 'Cameroon', slug: 'cameroon', phoneCode: '+237', continentCode: 'AF' },
  { iso2: 'CA', iso3: 'CAN', numericCode: '124', name: 'Canada', slug: 'canada', phoneCode: '+1', continentCode: 'NA' },
  { iso2: 'CV', iso3: 'CPV', numericCode: '132', name: 'Cape Verde', slug: 'cape-verde', phoneCode: '+238', continentCode: 'AF' },
  { iso2: 'CF', iso3: 'CAF', numericCode: '140', name: 'Central African Republic', slug: 'central-african-republic', phoneCode: '+236', continentCode: 'AF' },
  { iso2: 'TD', iso3: 'TCD', numericCode: '148', name: 'Chad', slug: 'chad', phoneCode: '+235', continentCode: 'AF' },
  { iso2: 'CL', iso3: 'CHL', numericCode: '152', name: 'Chile', slug: 'chile', phoneCode: '+56', continentCode: 'SA' },
  { iso2: 'CN', iso3: 'CHN', numericCode: '156', name: 'China', slug: 'china', phoneCode: '+86', continentCode: 'AS' },
  { iso2: 'CO', iso3: 'COL', numericCode: '170', name: 'Colombia', slug: 'colombia', phoneCode: '+57', continentCode: 'SA' },
  { iso2: 'KM', iso3: 'COM', numericCode: '174', name: 'Comoros', slug: 'comoros', phoneCode: '+269', continentCode: 'AF' },
  { iso2: 'CG', iso3: 'COG', numericCode: '178', name: 'Republic of the Congo', slug: 'republic-of-the-congo', phoneCode: '+242', continentCode: 'AF' },
  { iso2: 'CD', iso3: 'COD', numericCode: '180', name: 'Democratic Republic of the Congo', slug: 'democratic-republic-of-the-congo', phoneCode: '+243', continentCode: 'AF' },
  { iso2: 'CR', iso3: 'CRI', numericCode: '188', name: 'Costa Rica', slug: 'costa-rica', phoneCode: '+506', continentCode: 'NA' },
  { iso2: 'CI', iso3: 'CIV', numericCode: '384', name: "Côte d'Ivoire", slug: 'cote-divoire', phoneCode: '+225', continentCode: 'AF' },
  { iso2: 'HR', iso3: 'HRV', numericCode: '191', name: 'Croatia', slug: 'croatia', phoneCode: '+385', continentCode: 'EU' },
  { iso2: 'CU', iso3: 'CUB', numericCode: '192', name: 'Cuba', slug: 'cuba', phoneCode: '+53', continentCode: 'NA' },
  { iso2: 'CY', iso3: 'CYP', numericCode: '196', name: 'Cyprus', slug: 'cyprus', phoneCode: '+357', continentCode: 'AS' },
  { iso2: 'CZ', iso3: 'CZE', numericCode: '203', name: 'Czechia', slug: 'czechia', phoneCode: '+420', continentCode: 'EU' },

  { iso2: 'DK', iso3: 'DNK', numericCode: '208', name: 'Denmark', slug: 'denmark', phoneCode: '+45', continentCode: 'EU' },
  { iso2: 'DJ', iso3: 'DJI', numericCode: '262', name: 'Djibouti', slug: 'djibouti', phoneCode: '+253', continentCode: 'AF' },
  { iso2: 'DM', iso3: 'DMA', numericCode: '212', name: 'Dominica', slug: 'dominica', phoneCode: '+1-767', continentCode: 'NA' },
  { iso2: 'DO', iso3: 'DOM', numericCode: '214', name: 'Dominican Republic', slug: 'dominican-republic', phoneCode: '+1-809', continentCode: 'NA' },

  { iso2: 'EC', iso3: 'ECU', numericCode: '218', name: 'Ecuador', slug: 'ecuador', phoneCode: '+593', continentCode: 'SA' },
  { iso2: 'EG', iso3: 'EGY', numericCode: '818', name: 'Egypt', slug: 'egypt', phoneCode: '+20', continentCode: 'AF' },
  { iso2: 'SV', iso3: 'SLV', numericCode: '222', name: 'El Salvador', slug: 'el-salvador', phoneCode: '+503', continentCode: 'NA' },
  { iso2: 'GQ', iso3: 'GNQ', numericCode: '226', name: 'Equatorial Guinea', slug: 'equatorial-guinea', phoneCode: '+240', continentCode: 'AF' },
  { iso2: 'ER', iso3: 'ERI', numericCode: '232', name: 'Eritrea', slug: 'eritrea', phoneCode: '+291', continentCode: 'AF' },
  { iso2: 'EE', iso3: 'EST', numericCode: '233', name: 'Estonia', slug: 'estonia', phoneCode: '+372', continentCode: 'EU' },
  { iso2: 'SZ', iso3: 'SWZ', numericCode: '748', name: 'Eswatini', slug: 'eswatini', phoneCode: '+268', continentCode: 'AF' },
  { iso2: 'ET', iso3: 'ETH', numericCode: '231', name: 'Ethiopia', slug: 'ethiopia', phoneCode: '+251', continentCode: 'AF' },

  { iso2: 'FJ', iso3: 'FJI', numericCode: '242', name: 'Fiji', slug: 'fiji', phoneCode: '+679', continentCode: 'OC' },
  { iso2: 'FI', iso3: 'FIN', numericCode: '246', name: 'Finland', slug: 'finland', phoneCode: '+358', continentCode: 'EU' },
  { iso2: 'FR', iso3: 'FRA', numericCode: '250', name: 'France', slug: 'france', phoneCode: '+33', continentCode: 'EU' },

  { iso2: 'GA', iso3: 'GAB', numericCode: '266', name: 'Gabon', slug: 'gabon', phoneCode: '+241', continentCode: 'AF' },
  { iso2: 'GM', iso3: 'GMB', numericCode: '270', name: 'Gambia', slug: 'gambia', phoneCode: '+220', continentCode: 'AF' },
  { iso2: 'GE', iso3: 'GEO', numericCode: '268', name: 'Georgia', slug: 'georgia', phoneCode: '+995', continentCode: 'AS' },
  { iso2: 'DE', iso3: 'DEU', numericCode: '276', name: 'Germany', slug: 'germany', phoneCode: '+49', continentCode: 'EU' },
  { iso2: 'GH', iso3: 'GHA', numericCode: '288', name: 'Ghana', slug: 'ghana', phoneCode: '+233', continentCode: 'AF' },
  { iso2: 'GR', iso3: 'GRC', numericCode: '300', name: 'Greece', slug: 'greece', phoneCode: '+30', continentCode: 'EU' },
  { iso2: 'GD', iso3: 'GRD', numericCode: '308', name: 'Grenada', slug: 'grenada', phoneCode: '+1-473', continentCode: 'NA' },
  { iso2: 'GT', iso3: 'GTM', numericCode: '320', name: 'Guatemala', slug: 'guatemala', phoneCode: '+502', continentCode: 'NA' },
  { iso2: 'GN', iso3: 'GIN', numericCode: '324', name: 'Guinea', slug: 'guinea', phoneCode: '+224', continentCode: 'AF' },
  { iso2: 'GW', iso3: 'GNB', numericCode: '624', name: 'Guinea-Bissau', slug: 'guinea-bissau', phoneCode: '+245', continentCode: 'AF' },
  { iso2: 'GY', iso3: 'GUY', numericCode: '328', name: 'Guyana', slug: 'guyana', phoneCode: '+592', continentCode: 'SA' },

  { iso2: 'HT', iso3: 'HTI', numericCode: '332', name: 'Haiti', slug: 'haiti', phoneCode: '+509', continentCode: 'NA' },
  { iso2: 'HN', iso3: 'HND', numericCode: '340', name: 'Honduras', slug: 'honduras', phoneCode: '+504', continentCode: 'NA' },
  { iso2: 'HU', iso3: 'HUN', numericCode: '348', name: 'Hungary', slug: 'hungary', phoneCode: '+36', continentCode: 'EU' },

  { iso2: 'IS', iso3: 'ISL', numericCode: '352', name: 'Iceland', slug: 'iceland', phoneCode: '+354', continentCode: 'EU' },
  { iso2: 'IN', iso3: 'IND', numericCode: '356', name: 'India', slug: 'india', phoneCode: '+91', continentCode: 'AS' },
  { iso2: 'ID', iso3: 'IDN', numericCode: '360', name: 'Indonesia', slug: 'indonesia', phoneCode: '+62', continentCode: 'AS' },
  { iso2: 'IR', iso3: 'IRN', numericCode: '364', name: 'Iran', slug: 'iran', phoneCode: '+98', continentCode: 'AS' },
  { iso2: 'IQ', iso3: 'IRQ', numericCode: '368', name: 'Iraq', slug: 'iraq', phoneCode: '+964', continentCode: 'AS' },
  { iso2: 'IE', iso3: 'IRL', numericCode: '372', name: 'Ireland', slug: 'ireland', phoneCode: '+353', continentCode: 'EU' },
  { iso2: 'IL', iso3: 'ISR', numericCode: '376', name: 'Israel', slug: 'israel', phoneCode: '+972', continentCode: 'AS' },
  { iso2: 'IT', iso3: 'ITA', numericCode: '380', name: 'Italy', slug: 'italy', phoneCode: '+39', continentCode: 'EU' },

  { iso2: 'JM', iso3: 'JAM', numericCode: '388', name: 'Jamaica', slug: 'jamaica', phoneCode: '+1-876', continentCode: 'NA' },
  { iso2: 'JP', iso3: 'JPN', numericCode: '392', name: 'Japan', slug: 'japan', phoneCode: '+81', continentCode: 'AS' },
  { iso2: 'JO', iso3: 'JOR', numericCode: '400', name: 'Jordan', slug: 'jordan', phoneCode: '+962', continentCode: 'AS' },

  { iso2: 'KZ', iso3: 'KAZ', numericCode: '398', name: 'Kazakhstan', slug: 'kazakhstan', phoneCode: '+7', continentCode: 'AS' },
  { iso2: 'KE', iso3: 'KEN', numericCode: '404', name: 'Kenya', slug: 'kenya', phoneCode: '+254', continentCode: 'AF' },
  { iso2: 'KI', iso3: 'KIR', numericCode: '296', name: 'Kiribati', slug: 'kiribati', phoneCode: '+686', continentCode: 'OC' },
  { iso2: 'KW', iso3: 'KWT', numericCode: '414', name: 'Kuwait', slug: 'kuwait', phoneCode: '+965', continentCode: 'AS' },
  { iso2: 'KG', iso3: 'KGZ', numericCode: '417', name: 'Kyrgyzstan', slug: 'kyrgyzstan', phoneCode: '+996', continentCode: 'AS' },

  { iso2: 'LA', iso3: 'LAO', numericCode: '418', name: 'Laos', slug: 'laos', phoneCode: '+856', continentCode: 'AS' },
  { iso2: 'LV', iso3: 'LVA', numericCode: '428', name: 'Latvia', slug: 'latvia', phoneCode: '+371', continentCode: 'EU' },
  { iso2: 'LB', iso3: 'LBN', numericCode: '422', name: 'Lebanon', slug: 'lebanon', phoneCode: '+961', continentCode: 'AS' },
  { iso2: 'LS', iso3: 'LSO', numericCode: '426', name: 'Lesotho', slug: 'lesotho', phoneCode: '+266', continentCode: 'AF' },
  { iso2: 'LR', iso3: 'LBR', numericCode: '430', name: 'Liberia', slug: 'liberia', phoneCode: '+231', continentCode: 'AF' },
  { iso2: 'LY', iso3: 'LBY', numericCode: '434', name: 'Libya', slug: 'libya', phoneCode: '+218', continentCode: 'AF' },
  { iso2: 'LI', iso3: 'LIE', numericCode: '438', name: 'Liechtenstein', slug: 'liechtenstein', phoneCode: '+423', continentCode: 'EU' },
  { iso2: 'LT', iso3: 'LTU', numericCode: '440', name: 'Lithuania', slug: 'lithuania', phoneCode: '+370', continentCode: 'EU' },
  { iso2: 'LU', iso3: 'LUX', numericCode: '442', name: 'Luxembourg', slug: 'luxembourg', phoneCode: '+352', continentCode: 'EU' },

  { iso2: 'MG', iso3: 'MDG', numericCode: '450', name: 'Madagascar', slug: 'madagascar', phoneCode: '+261', continentCode: 'AF' },
  { iso2: 'MW', iso3: 'MWI', numericCode: '454', name: 'Malawi', slug: 'malawi', phoneCode: '+265', continentCode: 'AF' },
  { iso2: 'MY', iso3: 'MYS', numericCode: '458', name: 'Malaysia', slug: 'malaysia', phoneCode: '+60', continentCode: 'AS' },
  { iso2: 'MV', iso3: 'MDV', numericCode: '462', name: 'Maldives', slug: 'maldives', phoneCode: '+960', continentCode: 'AS' },
  { iso2: 'ML', iso3: 'MLI', numericCode: '466', name: 'Mali', slug: 'mali', phoneCode: '+223', continentCode: 'AF' },
  { iso2: 'MT', iso3: 'MLT', numericCode: '470', name: 'Malta', slug: 'malta', phoneCode: '+356', continentCode: 'EU' },
  { iso2: 'MR', iso3: 'MRT', numericCode: '478', name: 'Mauritania', slug: 'mauritania', phoneCode: '+222', continentCode: 'AF' },
  { iso2: 'MU', iso3: 'MUS', numericCode: '480', name: 'Mauritius', slug: 'mauritius', phoneCode: '+230', continentCode: 'AF' },
  { iso2: 'MX', iso3: 'MEX', numericCode: '484', name: 'Mexico', slug: 'mexico', phoneCode: '+52', continentCode: 'NA' },
  { iso2: 'MD', iso3: 'MDA', numericCode: '498', name: 'Moldova', slug: 'moldova', phoneCode: '+373', continentCode: 'EU' },
  { iso2: 'MC', iso3: 'MCO', numericCode: '492', name: 'Monaco', slug: 'monaco', phoneCode: '+377', continentCode: 'EU' },
  { iso2: 'MN', iso3: 'MNG', numericCode: '496', name: 'Mongolia', slug: 'mongolia', phoneCode: '+976', continentCode: 'AS' },
  { iso2: 'ME', iso3: 'MNE', numericCode: '499', name: 'Montenegro', slug: 'montenegro', phoneCode: '+382', continentCode: 'EU' },
  { iso2: 'MA', iso3: 'MAR', numericCode: '504', name: 'Morocco', slug: 'morocco', phoneCode: '+212', continentCode: 'AF' },
  { iso2: 'MZ', iso3: 'MOZ', numericCode: '508', name: 'Mozambique', slug: 'mozambique', phoneCode: '+258', continentCode: 'AF' },
  { iso2: 'MM', iso3: 'MMR', numericCode: '104', name: 'Myanmar', slug: 'myanmar', phoneCode: '+95', continentCode: 'AS' },

  { iso2: 'NA', iso3: 'NAM', numericCode: '516', name: 'Namibia', slug: 'namibia', phoneCode: '+264', continentCode: 'AF' },
  { iso2: 'NP', iso3: 'NPL', numericCode: '524', name: 'Nepal', slug: 'nepal', phoneCode: '+977', continentCode: 'AS' },
  { iso2: 'NL', iso3: 'NLD', numericCode: '528', name: 'Netherlands', slug: 'netherlands', phoneCode: '+31', continentCode: 'EU' },
  { iso2: 'NZ', iso3: 'NZL', numericCode: '554', name: 'New Zealand', slug: 'new-zealand', phoneCode: '+64', continentCode: 'OC' },
  { iso2: 'NI', iso3: 'NIC', numericCode: '558', name: 'Nicaragua', slug: 'nicaragua', phoneCode: '+505', continentCode: 'NA' },
  { iso2: 'NE', iso3: 'NER', numericCode: '562', name: 'Niger', slug: 'niger', phoneCode: '+227', continentCode: 'AF' },
  { iso2: 'NG', iso3: 'NGA', numericCode: '566', name: 'Nigeria', slug: 'nigeria', phoneCode: '+234', continentCode: 'AF' },
  { iso2: 'MK', iso3: 'MKD', numericCode: '807', name: 'North Macedonia', slug: 'north-macedonia', phoneCode: '+389', continentCode: 'EU' },
  { iso2: 'NO', iso3: 'NOR', numericCode: '578', name: 'Norway', slug: 'norway', phoneCode: '+47', continentCode: 'EU' },

  { iso2: 'OM', iso3: 'OMN', numericCode: '512', name: 'Oman', slug: 'oman', phoneCode: '+968', continentCode: 'AS' },

  { iso2: 'PK', iso3: 'PAK', numericCode: '586', name: 'Pakistan', slug: 'pakistan', phoneCode: '+92', continentCode: 'AS' },
  { iso2: 'PA', iso3: 'PAN', numericCode: '591', name: 'Panama', slug: 'panama', phoneCode: '+507', continentCode: 'NA' },
  { iso2: 'PG', iso3: 'PNG', numericCode: '598', name: 'Papua New Guinea', slug: 'papua-new-guinea', phoneCode: '+675', continentCode: 'OC' },
  { iso2: 'PY', iso3: 'PRY', numericCode: '600', name: 'Paraguay', slug: 'paraguay', phoneCode: '+595', continentCode: 'SA' },
  { iso2: 'PE', iso3: 'PER', numericCode: '604', name: 'Peru', slug: 'peru', phoneCode: '+51', continentCode: 'SA' },
  { iso2: 'PH', iso3: 'PHL', numericCode: '608', name: 'Philippines', slug: 'philippines', phoneCode: '+63', continentCode: 'AS' },
  { iso2: 'PL', iso3: 'POL', numericCode: '616', name: 'Poland', slug: 'poland', phoneCode: '+48', continentCode: 'EU' },
  { iso2: 'PT', iso3: 'PRT', numericCode: '620', name: 'Portugal', slug: 'portugal', phoneCode: '+351', continentCode: 'EU' },

  { iso2: 'QA', iso3: 'QAT', numericCode: '634', name: 'Qatar', slug: 'qatar', phoneCode: '+974', continentCode: 'AS' },

  { iso2: 'RO', iso3: 'ROU', numericCode: '642', name: 'Romania', slug: 'romania', phoneCode: '+40', continentCode: 'EU' },
  { iso2: 'RU', iso3: 'RUS', numericCode: '643', name: 'Russia', slug: 'russia', phoneCode: '+7', continentCode: 'EU' },
  { iso2: 'RW', iso3: 'RWA', numericCode: '646', name: 'Rwanda', slug: 'rwanda', phoneCode: '+250', continentCode: 'AF' },

  { iso2: 'KN', iso3: 'KNA', numericCode: '659', name: 'Saint Kitts and Nevis', slug: 'saint-kitts-and-nevis', phoneCode: '+1-869', continentCode: 'NA' },
  { iso2: 'LC', iso3: 'LCA', numericCode: '662', name: 'Saint Lucia', slug: 'saint-lucia', phoneCode: '+1-758', continentCode: 'NA' },
  { iso2: 'VC', iso3: 'VCT', numericCode: '670', name: 'Saint Vincent and the Grenadines', slug: 'saint-vincent-and-the-grenadines', phoneCode: '+1-784', continentCode: 'NA' },
  { iso2: 'WS', iso3: 'WSM', numericCode: '882', name: 'Samoa', slug: 'samoa', phoneCode: '+685', continentCode: 'OC' },
  { iso2: 'SM', iso3: 'SMR', numericCode: '674', name: 'San Marino', slug: 'san-marino', phoneCode: '+378', continentCode: 'EU' },
  { iso2: 'ST', iso3: 'STP', numericCode: '678', name: 'São Tomé and Príncipe', slug: 'sao-tome-and-principe', phoneCode: '+239', continentCode: 'AF' },
  { iso2: 'SA', iso3: 'SAU', numericCode: '682', name: 'Saudi Arabia', slug: 'saudi-arabia', phoneCode: '+966', continentCode: 'AS' },
  { iso2: 'SN', iso3: 'SEN', numericCode: '686', name: 'Senegal', slug: 'senegal', phoneCode: '+221', continentCode: 'AF' },
  { iso2: 'RS', iso3: 'SRB', numericCode: '688', name: 'Serbia', slug: 'serbia', phoneCode: '+381', continentCode: 'EU' },
  { iso2: 'SC', iso3: 'SYC', numericCode: '690', name: 'Seychelles', slug: 'seychelles', phoneCode: '+248', continentCode: 'AF' },
  { iso2: 'SL', iso3: 'SLE', numericCode: '694', name: 'Sierra Leone', slug: 'sierra-leone', phoneCode: '+232', continentCode: 'AF' },
  { iso2: 'SG', iso3: 'SGP', numericCode: '702', name: 'Singapore', slug: 'singapore', phoneCode: '+65', continentCode: 'AS' },
  { iso2: 'SK', iso3: 'SVK', numericCode: '703', name: 'Slovakia', slug: 'slovakia', phoneCode: '+421', continentCode: 'EU' },
  { iso2: 'SI', iso3: 'SVN', numericCode: '705', name: 'Slovenia', slug: 'slovenia', phoneCode: '+386', continentCode: 'EU' },
  { iso2: 'SB', iso3: 'SLB', numericCode: '090', name: 'Solomon Islands', slug: 'solomon-islands', phoneCode: '+677', continentCode: 'OC' },
  { iso2: 'SO', iso3: 'SOM', numericCode: '706', name: 'Somalia', slug: 'somalia', phoneCode: '+252', continentCode: 'AF' },
  { iso2: 'ZA', iso3: 'ZAF', numericCode: '710', name: 'South Africa', slug: 'south-africa', phoneCode: '+27', continentCode: 'AF' },
  { iso2: 'KR', iso3: 'KOR', numericCode: '410', name: 'South Korea', slug: 'south-korea', phoneCode: '+82', continentCode: 'AS' },
  { iso2: 'ES', iso3: 'ESP', numericCode: '724', name: 'Spain', slug: 'spain', phoneCode: '+34', continentCode: 'EU' },
  { iso2: 'LK', iso3: 'LKA', numericCode: '144', name: 'Sri Lanka', slug: 'sri-lanka', phoneCode: '+94', continentCode: 'AS' },
  { iso2: 'SD', iso3: 'SDN', numericCode: '729', name: 'Sudan', slug: 'sudan', phoneCode: '+249', continentCode: 'AF' },
  { iso2: 'SR', iso3: 'SUR', numericCode: '740', name: 'Suriname', slug: 'suriname', phoneCode: '+597', continentCode: 'SA' },
  { iso2: 'SE', iso3: 'SWE', numericCode: '752', name: 'Sweden', slug: 'sweden', phoneCode: '+46', continentCode: 'EU' },
  { iso2: 'CH', iso3: 'CHE', numericCode: '756', name: 'Switzerland', slug: 'switzerland', phoneCode: '+41', continentCode: 'EU' },
  { iso2: 'SY', iso3: 'SYR', numericCode: '760', name: 'Syria', slug: 'syria', phoneCode: '+963', continentCode: 'AS' },

  { iso2: 'TW', iso3: 'TWN', numericCode: '158', name: 'Taiwan', slug: 'taiwan', phoneCode: '+886', continentCode: 'AS' },
  { iso2: 'TJ', iso3: 'TJK', numericCode: '762', name: 'Tajikistan', slug: 'tajikistan', phoneCode: '+992', continentCode: 'AS' },
  { iso2: 'TZ', iso3: 'TZA', numericCode: '834', name: 'Tanzania', slug: 'tanzania', phoneCode: '+255', continentCode: 'AF' },
  { iso2: 'TH', iso3: 'THA', numericCode: '764', name: 'Thailand', slug: 'thailand', phoneCode: '+66', continentCode: 'AS' },
  { iso2: 'TL', iso3: 'TLS', numericCode: '626', name: 'Timor-Leste', slug: 'timor-leste', phoneCode: '+670', continentCode: 'AS' },
  { iso2: 'TG', iso3: 'TGO', numericCode: '768', name: 'Togo', slug: 'togo', phoneCode: '+228', continentCode: 'AF' },
  { iso2: 'TO', iso3: 'TON', numericCode: '776', name: 'Tonga', slug: 'tonga', phoneCode: '+676', continentCode: 'OC' },
  { iso2: 'TT', iso3: 'TTO', numericCode: '780', name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago', phoneCode: '+1-868', continentCode: 'NA' },
  { iso2: 'TN', iso3: 'TUN', numericCode: '788', name: 'Tunisia', slug: 'tunisia', phoneCode: '+216', continentCode: 'AF' },
  { iso2: 'TR', iso3: 'TUR', numericCode: '792', name: 'Türkiye', slug: 'turkiye', phoneCode: '+90', continentCode: 'AS' },
  { iso2: 'TM', iso3: 'TKM', numericCode: '795', name: 'Turkmenistan', slug: 'turkmenistan', phoneCode: '+993', continentCode: 'AS' },
  { iso2: 'TV', iso3: 'TUV', numericCode: '798', name: 'Tuvalu', slug: 'tuvalu', phoneCode: '+688', continentCode: 'OC' },

  { iso2: 'UG', iso3: 'UGA', numericCode: '800', name: 'Uganda', slug: 'uganda', phoneCode: '+256', continentCode: 'AF' },
  { iso2: 'UA', iso3: 'UKR', numericCode: '804', name: 'Ukraine', slug: 'ukraine', phoneCode: '+380', continentCode: 'EU' },
  { iso2: 'AE', iso3: 'ARE', numericCode: '784', name: 'United Arab Emirates', slug: 'united-arab-emirates', phoneCode: '+971', continentCode: 'AS' },
  { iso2: 'GB', iso3: 'GBR', numericCode: '826', name: 'United Kingdom', slug: 'united-kingdom', phoneCode: '+44', continentCode: 'EU' },
  { iso2: 'US', iso3: 'USA', numericCode: '840', name: 'United States', slug: 'united-states', phoneCode: '+1', continentCode: 'NA' },
  { iso2: 'UY', iso3: 'URY', numericCode: '858', name: 'Uruguay', slug: 'uruguay', phoneCode: '+598', continentCode: 'SA' },
  { iso2: 'UZ', iso3: 'UZB', numericCode: '860', name: 'Uzbekistan', slug: 'uzbekistan', phoneCode: '+998', continentCode: 'AS' },

  { iso2: 'VU', iso3: 'VUT', numericCode: '548', name: 'Vanuatu', slug: 'vanuatu', phoneCode: '+678', continentCode: 'OC' },
  { iso2: 'VA', iso3: 'VAT', numericCode: '336', name: 'Vatican City', slug: 'vatican-city', phoneCode: '+379', continentCode: 'EU' },
  { iso2: 'VE', iso3: 'VEN', numericCode: '862', name: 'Venezuela', slug: 'venezuela', phoneCode: '+58', continentCode: 'SA' },
  { iso2: 'VN', iso3: 'VNM', numericCode: '704', name: 'Vietnam', slug: 'vietnam', phoneCode: '+84', continentCode: 'AS' },

  { iso2: 'YE', iso3: 'YEM', numericCode: '887', name: 'Yemen', slug: 'yemen', phoneCode: '+967', continentCode: 'AS' },

  { iso2: 'ZM', iso3: 'ZMB', numericCode: '894', name: 'Zambia', slug: 'zambia', phoneCode: '+260', continentCode: 'AF' },
  { iso2: 'ZW', iso3: 'ZWE', numericCode: '716', name: 'Zimbabwe', slug: 'zimbabwe', phoneCode: '+263', continentCode: 'AF' }
];


const INDIA_STATES = [
  { code: 'AP', name: 'Andhra Pradesh', slug: 'andhra-pradesh', type: 'STATE' },
  { code: 'AR', name: 'Arunachal Pradesh', slug: 'arunachal-pradesh', type: 'STATE' },
  { code: 'AS', name: 'Assam', slug: 'assam', type: 'STATE' },
  { code: 'BR', name: 'Bihar', slug: 'bihar', type: 'STATE' },
  { code: 'CG', name: 'Chhattisgarh', slug: 'chhattisgarh', type: 'STATE' },
  { code: 'GA', name: 'Goa', slug: 'goa', type: 'STATE' },
  { code: 'GJ', name: 'Gujarat', slug: 'gujarat', type: 'STATE' },
  { code: 'HR', name: 'Haryana', slug: 'haryana', type: 'STATE' },
  { code: 'HP', name: 'Himachal Pradesh', slug: 'himachal-pradesh', type: 'STATE' },
  { code: 'JH', name: 'Jharkhand', slug: 'jharkhand', type: 'STATE' },
  { code: 'KA', name: 'Karnataka', slug: 'karnataka', type: 'STATE' },
  { code: 'KL', name: 'Kerala', slug: 'kerala', type: 'STATE' },
  { code: 'MP', name: 'Madhya Pradesh', slug: 'madhya-pradesh', type: 'STATE' },
  { code: 'MH', name: 'Maharashtra', slug: 'maharashtra', type: 'STATE' },
  { code: 'MN', name: 'Manipur', slug: 'manipur', type: 'STATE' },
  { code: 'ML', name: 'Meghalaya', slug: 'meghalaya', type: 'STATE' },
  { code: 'MZ', name: 'Mizoram', slug: 'mizoram', type: 'STATE' },
  { code: 'NL', name: 'Nagaland', slug: 'nagaland', type: 'STATE' },
  { code: 'OD', name: 'Odisha', slug: 'odisha', type: 'STATE' },
  { code: 'PB', name: 'Punjab', slug: 'punjab', type: 'STATE' },
  { code: 'RJ', name: 'Rajasthan', slug: 'rajasthan', type: 'STATE' },
  { code: 'SK', name: 'Sikkim', slug: 'sikkim', type: 'STATE' },
  { code: 'TN', name: 'Tamil Nadu', slug: 'tamil-nadu', type: 'STATE' },
  { code: 'TG', name: 'Telangana', slug: 'telangana', type: 'STATE' },
  { code: 'TR', name: 'Tripura', slug: 'tripura', type: 'STATE' },
  { code: 'UP', name: 'Uttar Pradesh', slug: 'uttar-pradesh', type: 'STATE' },
  { code: 'UK', name: 'Uttarakhand', slug: 'uttarakhand', type: 'STATE' },
  { code: 'WB', name: 'West Bengal', slug: 'west-bengal', type: 'STATE' },

  { code: 'AN', name: 'Andaman and Nicobar Islands', slug: 'andaman-and-nicobar-islands', type: 'UNION_TERRITORY' },
  { code: 'CH', name: 'Chandigarh', slug: 'chandigarh', type: 'UNION_TERRITORY' },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu', slug: 'dadra-and-nagar-haveli-and-daman-and-diu', type: 'UNION_TERRITORY' },
  { code: 'DL', name: 'Delhi', slug: 'delhi', type: 'UNION_TERRITORY' },
  { code: 'JK', name: 'Jammu and Kashmir', slug: 'jammu-and-kashmir', type: 'UNION_TERRITORY' },
  { code: 'LA', name: 'Ladakh', slug: 'ladakh', type: 'UNION_TERRITORY' },
  { code: 'LD', name: 'Lakshadweep', slug: 'lakshadweep', type: 'UNION_TERRITORY' },
  { code: 'PY', name: 'Puducherry', slug: 'puducherry', type: 'UNION_TERRITORY' }
];


const INDIA_CITIES = {
  AP: [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Kadapa',
    'Anantapur',
    'Eluru',
    'Ongole',
    'Machilipatnam',
    'Srikakulam',
    'Vizianagaram',
    'Chittoor',
    'Hindupur',
    'Bhimavaram',
    'Tenali',
    'Proddatur',
    'Nandyal',
    'Adoni',
    'Madanapalle',
    'Gudivada',
    'Tadepalligudem',
    'Narasaraopet',
    'Chilakaluripet',
    'Amalapuram',
    'Tadipatri',
    'Dharmavaram',
    'Markapur',
    'Palakollu',
    'Tanuku',
    'Srikalahasti',
    'Puttur',
    'Bapatla',
    'Repalle',
    'Parvathipuram',
    'Bobbili',
    'Narsapur',
    'Yemmiganur',
    'Rayachoti',
    'Jammalamadugu',
    'Punganur',
    'Gooty'
  ],

  AR: [
    'Itanagar',
    'Naharlagun',
    'Tawang',
    'Pasighat',
    'Ziro',
    'Bomdila',
    'Along',
    'Tezu',
    'Roing',
    'Namsai',
    'Changlang',
    'Khonsa',
    'Seppa',
    'Daporijo',
    'Yingkiong',
    'Anini',
    'Aalo',
    'Basar',
    'Dirang',
    'Bhalukpong'
  ],

  AS: [
    'Guwahati',
    'Dibrugarh',
    'Silchar',
    'Jorhat',
    'Tezpur',
    'Nagaon',
    'Tinsukia',
    'Sivasagar',
    'Dhubri',
    'Bongaigaon',
    'Barpeta',
    'Goalpara',
    'North Lakhimpur',
    'Karimganj',
    'Hailakandi',
    'Diphu',
    'Mangaldoi',
    'Nalbari',
    'Kokrajhar',
    'Hojai',
    'Morigaon',
    'Golaghat',
    'Dhemaji',
    'Biswanath Chariali',
    'Mariani',
    'Digboi',
    'Duliajan',
    'Bokakhat',
    'Abhayapuri',
    'Pathsala',
    'Rangia',
    'Sualkuchi',
    'Titabor',
    'Naharkatia',
    'Margherita'
  ],

  BR: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
    'Ara',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Danapur',
    'Saharsa',
    'Hajipur',
    'Sasaram',
    'Dehri',
    'Bettiah',
    'Motihari',
    'Bagaha',
    'Siwan',
    'Buxar',
    'Kishanganj',
    'Jamalpur',
    'Jehanabad',
    'Aurangabad',
    'Nawada',
    'Araria',
    'Supaul',
    'Madhepura',
    'Sitamarhi',
    'Madhubani',
    'Samastipur',
    'Hazaribagh',
    'Khagaria',
    'Lakhisarai',
    'Sheikhpura',
    'Jamui',
    'Banka',
    'Saran',
    'Vaishali'
  ],

  CG: [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Jagdalpur',
    'Ambikapur',
    'Raigarh',
    'Dhamtari',
    'Mahasamund',
    'Kanker',
    'Kawardha',
    'Janjgir',
    'Champa',
    'Bhatapara',
    'Baloda Bazar',
    'Balod',
    'Bemetara',
    'Dantewada',
    'Bijapur',
    'Sukma',
    'Narayanpur',
    'Kondagaon',
    'Surajpur',
    'Manendragarh',
    'Baikunthpur',
    'Jashpur Nagar',
    'Pathalgaon',
    'Mungeli'
  ],

  GA: [
    'Panaji',
    'Vasco da Gama',
    'Margao',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Curchorem',
    'Cuncolim',
    'Canacona',
    'Quepem',
    'Sanguem',
    'Valpoi',
    'Porvorim',
    'Calangute',
    'Candolim',
    'Arambol',
    'Anjuna',
    'Baga',
    'Dona Paula'
  ],

  GJ: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Nadiad',
    'Bharuch',
    'Vapi',
    'Navsari',
    'Mehsana',
    'Morbi',
    'Bhuj',
    'Porbandar',
    'Palanpur',
    'Gondal',
    'Godhra',
    'Surendranagar',
    'Veraval',
    'Botad',
    'Amreli',
    'Dahod',
    'Patan',
    'Himatnagar',
    'Modasa',
    'Deesa',
    'Kalol',
    'Sanand',
    'Bavla',
    'Dholka',
    'Mahuva',
    'Palitana',
    'Sihor',
    'Wadhwan',
    'Jetpur',
    'Dhoraji',
    'Gondal',
    'Jasdan',
    'Amreli',
    'Savarkundla',
    'Una',
    'Mundra',
    'Anjar',
    'Gandhidham',
    'Mandvi',
    'Abdasa',
    'Dwarka',
    'Khambhalia',
    'Dhrol',
    'Kalavad',
    'Bardoli',
    'Vyara',
    'Songadh',
    'Bilimora',
    'Valsad',
    'Dharampur',
    'Waghai',
    'Chhota Udaipur',
    'Halol',
    'Lunawada',
    'Santrampur',
    'Kapadvanj',
    'Kheda',
    'Petlad',
    'Umreth',
    'Khambhat',
    'Borsad',
    'Viramgam',
    'Dholera'
  ],

  HR: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Hisar',
    'Rohtak',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Yamunanagar',
    'Bhiwani',
    'Sirsa',
    'Rewari',
    'Palwal',
    'Bahadurgarh',
    'Jind',
    'Kaithal',
    'Kurukshetra',
    'Fatehabad',
    'Narnaul',
    'Mahendragarh',
    'Charkhi Dadri',
    'Tohana',
    'Hansi',
    'Fatehabad',
    'Ratia',
    'Narwana',
    'Safidon',
    'Gohana',
    'Samalkha',
    'Kalka',
    'Pinjore',
    'Jagadhri',
    'Shahabad',
    'Pehowa',
    'Ladwa',
    'Thanesar',
    'Dharuhera',
    'Bawal'
  ],

  HP: [
    'Shimla',
    'Dharamshala',
    'Solan',
    'Mandi',
    'Kullu',
    'Manali',
    'Hamirpur',
    'Una',
    'Bilaspur',
    'Chamba',
    'Kangra',
    'Nahan',
    'Paonta Sahib',
    'Baddi',
    'Nalagarh',
    'Parwanoo',
    'Sundernagar',
    'Rampur',
    'Rohru',
    'Theog',
    'Dalhousie',
    'Kasauli',
    'Keylong',
    'Kalpa',
    'Reckong Peo',
    'Bhuntar',
    'Banjar',
    'Jogindernagar',
    'Palampur',
    'Nurpur'
  ],

  JH: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro',
    'Deoghar',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Dumka',
    'Phusro',
    'Medininagar',
    'Chaibasa',
    'Gumla',
    'Lohardaga',
    'Simdega',
    'Pakur',
    'Godda',
    'Sahebganj',
    'Jamtara',
    'Latehar',
    'Chatra',
    'Koderma',
    'Garhwa',
    'Seraikela',
    'Khunti',
    'Madhupur',
    'Chakradharpur',
    'Adityapur',
    'Bundu',
    'Mango'
  ],

  KA: [
    'Bengaluru',
    'Mysuru',
    'Mangaluru',
    'Hubballi',
    'Dharwad',
    'Belagavi',
    'Kalaburagi',
    'Davangere',
    'Ballari',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Hassan',
    'Vijayapura',
    'Raichur',
    'Bidar',
    'Chikkamagaluru',
    'Mandya',
    'Kolar',
    'Hospet',
    'Gadag',
    'Bagalkot',
    'Haveri',
    'Chitradurga',
    'Koppal',
    'Madikeri',
    'Karwar',
    'Sirsi',
    'Dandeli',
    'Chikballapur',
    'Ramanagara',
    'Yadgir',
    'Bhadravati',
    'Robertsonpet',
    'Gokak',
    'Athani',
    'Sankeshwar',
    'Ilkal',
    'Jamkhandi',
    'Mudhol',
    'Gangavathi',
    'Sindhanur',
    'Manvi',
    'Hospet',
    'Harihar',
    'Ranebennur',
    'Sagar',
    'Tiptur',
    'Channapatna',
    'Kushalnagar'
  ],

  KL: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Kollam',
    'Thrissur',
    'Kannur',
    'Alappuzha',
    'Palakkad',
    'Kottayam',
    'Malappuram',
    'Kasaragod',
    'Manjeri',
    'Thalassery',
    'Ponnani',
    'Vatakara',
    'Kanhangad',
    'Kayamkulam',
    'Neyyattinkara',
    'Attingal',
    'Nedumangad',
    'Kottarakara',
    'Karunagappally',
    'Changanassery',
    'Pathanamthitta',
    'Adoor',
    'Thiruvalla',
    'Chalakudy',
    'Kodungallur',
    'Irinjalakuda',
    'Guruvayur',
    'Kunnamkulam',
    'Ottapalam',
    'Shoranur',
    'Perinthalmanna',
    'Tirur',
    'Kondotty',
    'Nilambur',
    'Kalpetta',
    'Sulthan Bathery',
    'Payyanur',
    'Taliparamba',
    'Iritty'
  ],

  MP: [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Burhanpur',
    'Khandwa',
    'Bhind',
    'Morena',
    'Chhindwara',
    'Shivpuri',
    'Vidisha',
    'Sehore',
    'Mandsaur',
    'Neemuch',
    'Damoh',
    'Katni',
    'Singrauli',
    'Hoshangabad',
    'Itarsi',
    'Betul',
    'Harda',
    'Raisen',
    'Rajgarh',
    'Shajapur',
    'Agar',
    'Dhar',
    'Khargone',
    'Barwani',
    'Alirajpur',
    'Jhabua',
    'Mandla',
    'Balaghat',
    'Narsinghpur',
    'Panna',
    'Chhatarpur',
    'Tikamgarh',
    'Datia',
    'Ashoknagar',
    'Sheopur'
  ],

  MH: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Nashik',
    'Thane',
    'Aurangabad',
    'Navi Mumbai',
    'Solapur',
    'Kolhapur',
    'Amravati',
    'Akola',
    'Nanded',
    'Sangli',
    'Jalgaon',
    'Latur',
    'Ahmednagar',
    'Satara',
    'Chandrapur',
    'Bhiwandi',
    'Vasai-Virar',
    'Mira-Bhayandar',
    'Malegaon',
    'Dhule',
    'Parbhani',
    'Jalna',
    'Beed',
    'Osmanabad',
    'Wardha',
    'Yavatmal',
    'Gondia',
    'Bhandara',
    'Ratnagiri',
    'Sindhudurg',
    'Baramati',
    'Panvel',
    'Kalyan',
    'Dombivli',
    'Ulhasnagar',
    'Karjat',
    'Lonavala',
    'Mahad',
    'Alibag',
    'Raigad',
    'Ichalkaranji',
    'Miraj',
    'Karad',
    'Sangamner',
    'Shrirampur',
    'Manmad',
    'Nandurbar',
    'Bhusawal',
    'Chalisgaon',
    'Wani',
    'Achalpur',
    'Washim',
    'Hingoli',
    'Buldhana',
    'Gadchiroli'
  ],

  MN: [
    'Imphal',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
    'Ukhrul',
    'Senapati',
    'Tamenglong',
    'Chandel',
    'Kakching',
    'Moreh',
    'Jiribam',
    'Moirang',
    'Noney',
    'Kangpokpi'
  ],

  ML: [
    'Shillong',
    'Tura',
    'Jowai',
    'Nongpoh',
    'Nongstoin',
    'Williamnagar',
    'Baghmara',
    'Resubelpara',
    'Mairang',
    'Khliehriat'
  ],

  MZ: [
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Kolasib',
    'Serchhip',
    'Lawngtlai',
    'Mamit',
    'Saiha',
    'Khawzawl',
    'Hnahthial'
  ],

  NL: [
    'Kohima',
    'Dimapur',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Mon',
    'Phek',
    'Zunheboto',
    'Kiphire',
    'Longleng',
    'Peren',
    'Chumoukedima',
    'Niuland',
    'Tseminyu'
  ],

  OD: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Baripada',
    'Jharsuguda',
    'Bargarh',
    'Rayagada',
    'Koraput',
    'Bhadrak',
    'Balangir',
    'Dhenkanal',
    'Angul',
    'Jajpur',
    'Kendrapara',
    'Jagatsinghpur',
    'Keonjhar',
    'Sundargarh',
    'Phulbani',
    'Barbil',
    'Paradeep',
    'Boudh',
    'Nabarangpur',
    'Malkangiri',
    'Nuapada',
    'Titlagarh',
    'Bhawanipatna',
    'Aska',
    'Bhanjanagar',
    'Jeypore',
    'Sunabeda'
  ],

  PB: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Pathankot',
    'Hoshiarpur',
    'Moga',
    'Batala',
    'Abohar',
    'Firozpur',
    'Sangrur',
    'Barnala',
    'Khanna',
    'Phagwara',
    'Kapurthala',
    'Muktsar',
    'Faridkot',
    'Fazilka',
    'Gurdaspur',
    'Nawanshahr',
    'Malerkotla',
    'Rajpura',
    'Zirakpur',
    'Derabassi',
    'Tarn Taran',
    'Rupnagar',
    'Anandpur Sahib',
    'Nangal',
    'Sunam',
    'Samana',
    'Nabha',
    'Dhuri',
    'Kotkapura'
  ],

  RJ: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bharatpur',
    'Bhilwara',
    'Sri Ganganagar',
    'Sikar',
    'Pali',
    'Tonk',
    'Kishangarh',
    'Chittorgarh',
    'Barmer',
    'Jaisalmer',
    'Bundi',
    'Dausa',
    'Hanumangarh',
    'Sawai Madhopur',
    'Jhunjhunu',
    'Nagaur',
    'Churu',
    'Banswara',
    'Dungarpur',
    'Pratapgarh',
    'Rajsamand',
    'Jhalawar',
    'Baran',
    'Dholpur',
    'Karauli',
    'Bhiwadi',
    'Behror',
    'Neemrana',
    'Kotputli',
    'Shahpura',
    'Phalodi',
    'Balotra',
    'Jalore',
    'Sirohi',
    'Abu Road',
    'Mount Abu',
    'Makrana',
    'Didwana',
    'Merta City',
    'Ladnun',
    'Sujangarh',
    'Nawalgarh',
    'Fatehpur',
    'Khandela',
    'Chomu',
    'Bagru',
    'Sanganer',
    'Kekri',
    'Beawar',
    'Nasirabad',
    'Shahpura',
    'Nimbahera',
    'Kapasan',
    'Rawatbhata',
    'Nathdwara',
    'Rajgarh',
    'Bari'
  ],

  SK: [
    'Gangtok',
    'Namchi',
    'Gyalshing',
    'Mangan',
    'Ravangla',
    'Jorethang',
    'Singtam',
    'Rangpo',
    'Pelling',
    'Nayabazar'
  ],

  TN: [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Dindigul',
    'Thanjavur',
    'Nagercoil',
    'Kanchipuram',
    'Karur',
    'Cuddalore',
    'Hosur',
    'Tirunelveli',
    'Avadi',
    'Tambaram',
    'Ambattur',
    'Tiruvallur',
    'Kumbakonam',
    'Rajapalayam',
    'Pudukkottai',
    'Sivakasi',
    'Nagapattinam',
    'Mayiladuthurai',
    'Namakkal',
    'Dharmapuri',
    'Krishnagiri',
    'Ariyalur',
    'Perambalur',
    'Villupuram',
    'Kallakurichi',
    'Tenkasi',
    'Virudhunagar',
    'Ramanathapuram',
    'Sivaganga',
    'Paramakudi',
    'Pollachi',
    'Udumalaipettai',
    'Mettupalayam',
    'Ooty',
    'Coonoor',
    'Gobichettipalayam',
    'Bhavani',
    'Sathyamangalam',
    'Namakkal',
    'Tiruchengode',
    'Arakkonam',
    'Ranipet',
    'Arcot',
    'Walajapet',
    'Gudiyatham',
    'Vaniyambadi',
    'Ambur',
    'Chengalpattu',
    'Mahabalipuram',
    'Poonamallee',
    'Maraimalai Nagar'
  ],

  TG: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Khammam',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Siddipet',
    'Jagtial',
    'Mancherial',
    'Nirmal',
    'Kamareddy',
    'Bodhan',
    'Vikarabad',
    'Wanaparthy',
    'Nagarkurnool',
    'Miryalaguda',
    'Kothagudem',
    'Bhadrachalam',
    'Mahabubabad',
    'Jangaon',
    'Bhupalpally',
    'Asifabad',
    'Medak',
    'Sangareddy',
    'Zaheerabad',
    'Tandur',
    'Gadwal',
    'Korutla',
    'Metpally',
    'Huzurabad',
    'Jammikunta',
    'Peddapalli',
    'Sircilla',
    'Bhongir',
    'Devarakonda'
  ],

  TR: [
    'Agartala',
    'Dharmanagar',
    'Udaipur',
    'Kailashahar',
    'Belonia',
    'Ambassa',
    'Khowai',
    'Teliamura',
    'Sabroom',
    'Sonamura',
    'Kamalpur'
  ],

  UP: [
    'Lucknow',
    'Kanpur',
    'Noida',
    'Agra',
    'Varanasi',
    'Prayagraj',
    'Ghaziabad',
    'Meerut',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Mathura',
    'Ayodhya',
    'Jhansi',
    'Firozabad',
    'Muzaffarnagar',
    'Rampur',
    'Farrukhabad',
    'Ghaziabad',
    'Hapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Bijnor',
    'Shahjahanpur',
    'Pilibhit',
    'Lakhimpur',
    'Sitapur',
    'Hardoi',
    'Unnao',
    'Rae Bareli',
    'Sultanpur',
    'Jaunpur',
    'Azamgarh',
    'Mau',
    'Ballia',
    'Ghazipur',
    'Mirzapur',
    'Robertsganj',
    'Basti',
    'Deoria',
    'Kushinagar',
    'Maharajganj',
    'Siddharthnagar',
    'Bahraich',
    'Barabanki',
    'Gonda',
    'Balrampur',
    'Shravasti',
    'Fatehpur',
    'Banda',
    'Chitrakoot',
    'Hamirpur',
    'Mahoba',
    'Lalitpur',
    'Mainpuri',
    'Etawah',
    'Auraiya',
    'Kannauj',
    'Etah',
    'Kasganj',
    'Badaun',
    'Khurja',
    'Modinagar',
    'Loni',
    'Vrindavan',
    'Kasganj',
    'Orai',
    'Kosi Kalan'
  ],

  UK: [
    'Dehradun',
    'Haridwar',
    'Rishikesh',
    'Haldwani',
    'Nainital',
    'Roorkee',
    'Rudrapur',
    'Kashipur',
    'Almora',
    'Mussoorie',
    'Pithoragarh',
    'Srinagar',
    'Kotdwar',
    'Ramnagar',
    'Khatima',
    'Lohaghat',
    'Champawat',
    'Bageshwar',
    'Ranikhet',
    'Pauri',
    'Tehri',
    'Uttarkashi',
    'Chamoli',
    'Gopeshwar',
    'Joshimath',
    'Karnaprayag',
    'Rudraprayag',
    'Kedarnath',
    'Badrinath',
    'Lansdowne',
    'Vikasnagar',
    'Doiwala',
    'Lalkuan',
    'Bazpur',
    'Jaspur',
    'Sitarganj'
  ],

  WB: [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Darjeeling',
    'Kharagpur',
    'Haldia',
    'Malda',
    'Bardhaman',
    'Jalpaiguri',
    'Berhampore',
    'English Bazar',
    'Raiganj',
    'Cooch Behar',
    'Alipurduar',
    'Balurghat',
    'Krishnanagar',
    'Ranaghat',
    'Kalyani',
    'Barrackpore',
    'Barasat',
    'Habra',
    'Bally',
    'Uluberia',
    'Serampore',
    'Chandannagar',
    'Bandel',
    'Chinsurah',
    'Bansberia',
    'Suri',
    'Bolpur',
    'Santiniketan',
    'Bankura',
    'Purulia',
    'Jhargram',
    'Midnapore',
    'Contai',
    'Tamluk',
    'Diamond Harbour',
    'Krishnanagar',
    'Nabadwip',
    'Bongaon',
    'Basirhat',
    'Dum Dum',
    'Salt Lake',
    'New Town'
  ],

  AN: [
    'Port Blair',
    'Diglipur',
    'Mayabunder',
    'Rangat',
    'Havelock Island',
    'Neil Island',
    'Car Nicobar',
    'Campbell Bay',
    'Little Andaman'
  ],

  CH: [
    'Chandigarh'
  ],

  DN: [
    'Daman',
    'Silvassa',
    'Diu',
    'Amli',
    'Naroli',
    'Khanvel',
    'Vapi'
  ],

  DL: [
    'New Delhi',
    'Delhi',
    'Dwarka',
    'Rohini',
    'Saket',
    'Karol Bagh',
    'Janakpuri',
    'Lajpat Nagar',
    'Vasant Kunj',
    'Pitampura',
    'Shahdara',
    'Mayur Vihar',
    'Najafgarh',
    'Narela',
    'Model Town',
    'Civil Lines',
    'Greater Kailash',
    'Connaught Place'
  ],

  JK: [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Kathua',
    'Udhampur',
    'Sopore',
    'Kupwara',
    'Pulwama',
    'Rajouri',
    'Poonch',
    'Doda',
    'Kishtwar',
    'Ramban',
    'Bandipora',
    'Budgam',
    'Ganderbal',
    'Shopian',
    'Kulgam',
    'Reasi',
    'Samba',
    'Bhaderwah',
    'Katra',
    'Gulmarg',
    'Pahalgam'
  ],

  LA: [
    'Leh',
    'Kargil',
    'Nubra',
    'Diskit',
    'Turtuk',
    'Padum',
    'Drass',
    'Khalatse',
    'Nyoma',
    'Hanle'
  ],

  LD: [
    'Kavaratti',
    'Agatti',
    'Amini',
    'Andrott',
    'Kalpeni',
    'Kadmat',
    'Kiltan',
    'Minicoy',
    'Chetlat',
    'Bitra'
  ],

  PY: [
    'Puducherry',
    'Karaikal',
    'Mahe',
    'Yanam',
    'Ozhukarai',
    'Villianur',
    'Ariyankuppam',
    'Bahour'
  ]
};

const PHONE_COUNTRY_CODES = [
  { countryCode: 'AF', iso3: 'AFG', name: 'Afghanistan', dialCode: '+93', slug: 'afghanistan' },
  { countryCode: 'AL', iso3: 'ALB', name: 'Albania', dialCode: '+355', slug: 'albania' },
  { countryCode: 'DZ', iso3: 'DZA', name: 'Algeria', dialCode: '+213', slug: 'algeria' },
  { countryCode: 'AD', iso3: 'AND', name: 'Andorra', dialCode: '+376', slug: 'andorra' },
  { countryCode: 'AO', iso3: 'AGO', name: 'Angola', dialCode: '+244', slug: 'angola' },
  { countryCode: 'AG', iso3: 'ATG', name: 'Antigua and Barbuda', dialCode: '+1-268', slug: 'antigua-and-barbuda' },
  { countryCode: 'AR', iso3: 'ARG', name: 'Argentina', dialCode: '+54', slug: 'argentina' },
  { countryCode: 'AM', iso3: 'ARM', name: 'Armenia', dialCode: '+374', slug: 'armenia' },
  { countryCode: 'AU', iso3: 'AUS', name: 'Australia', dialCode: '+61', slug: 'australia' },
  { countryCode: 'AT', iso3: 'AUT', name: 'Austria', dialCode: '+43', slug: 'austria' },
  { countryCode: 'AZ', iso3: 'AZE', name: 'Azerbaijan', dialCode: '+994', slug: 'azerbaijan' },

  { countryCode: 'BS', iso3: 'BHS', name: 'Bahamas', dialCode: '+1-242', slug: 'bahamas' },
  { countryCode: 'BH', iso3: 'BHR', name: 'Bahrain', dialCode: '+973', slug: 'bahrain' },
  { countryCode: 'BD', iso3: 'BGD', name: 'Bangladesh', dialCode: '+880', slug: 'bangladesh' },
  { countryCode: 'BB', iso3: 'BRB', name: 'Barbados', dialCode: '+1-246', slug: 'barbados' },
  { countryCode: 'BY', iso3: 'BLR', name: 'Belarus', dialCode: '+375', slug: 'belarus' },
  { countryCode: 'BE', iso3: 'BEL', name: 'Belgium', dialCode: '+32', slug: 'belgium' },
  { countryCode: 'BZ', iso3: 'BLZ', name: 'Belize', dialCode: '+501', slug: 'belize' },
  { countryCode: 'BJ', iso3: 'BEN', name: 'Benin', dialCode: '+229', slug: 'benin' },
  { countryCode: 'BT', iso3: 'BTN', name: 'Bhutan', dialCode: '+975', slug: 'bhutan' },
  { countryCode: 'BO', iso3: 'BOL', name: 'Bolivia', dialCode: '+591', slug: 'bolivia' },
  { countryCode: 'BA', iso3: 'BIH', name: 'Bosnia and Herzegovina', dialCode: '+387', slug: 'bosnia-and-herzegovina' },
  { countryCode: 'BW', iso3: 'BWA', name: 'Botswana', dialCode: '+267', slug: 'botswana' },
  { countryCode: 'BR', iso3: 'BRA', name: 'Brazil', dialCode: '+55', slug: 'brazil' },
  { countryCode: 'BN', iso3: 'BRN', name: 'Brunei', dialCode: '+673', slug: 'brunei' },
  { countryCode: 'BG', iso3: 'BGR', name: 'Bulgaria', dialCode: '+359', slug: 'bulgaria' },
  { countryCode: 'BF', iso3: 'BFA', name: 'Burkina Faso', dialCode: '+226', slug: 'burkina-faso' },
  { countryCode: 'BI', iso3: 'BDI', name: 'Burundi', dialCode: '+257', slug: 'burundi' },

  { countryCode: 'CV', iso3: 'CPV', name: 'Cabo Verde', dialCode: '+238', slug: 'cabo-verde' },
  { countryCode: 'KH', iso3: 'KHM', name: 'Cambodia', dialCode: '+855', slug: 'cambodia' },
  { countryCode: 'CM', iso3: 'CMR', name: 'Cameroon', dialCode: '+237', slug: 'cameroon' },
  { countryCode: 'CA', iso3: 'CAN', name: 'Canada', dialCode: '+1', slug: 'canada' },
  { countryCode: 'CF', iso3: 'CAF', name: 'Central African Republic', dialCode: '+236', slug: 'central-african-republic' },
  { countryCode: 'TD', iso3: 'TCD', name: 'Chad', dialCode: '+235', slug: 'chad' },
  { countryCode: 'CL', iso3: 'CHL', name: 'Chile', dialCode: '+56', slug: 'chile' },
  { countryCode: 'CN', iso3: 'CHN', name: 'China', dialCode: '+86', slug: 'china' },
  { countryCode: 'CO', iso3: 'COL', name: 'Colombia', dialCode: '+57', slug: 'colombia' },
  { countryCode: 'KM', iso3: 'COM', name: 'Comoros', dialCode: '+269', slug: 'comoros' },
  { countryCode: 'CG', iso3: 'COG', name: 'Republic of the Congo', dialCode: '+242', slug: 'republic-of-the-congo' },
  { countryCode: 'CD', iso3: 'COD', name: 'Democratic Republic of the Congo', dialCode: '+243', slug: 'democratic-republic-of-the-congo' },
  { countryCode: 'CR', iso3: 'CRI', name: 'Costa Rica', dialCode: '+506', slug: 'costa-rica' },
  { countryCode: 'CI', iso3: 'CIV', name: "Côte d'Ivoire", dialCode: '+225', slug: 'cote-divoire' },
  { countryCode: 'HR', iso3: 'HRV', name: 'Croatia', dialCode: '+385', slug: 'croatia' },
  { countryCode: 'CU', iso3: 'CUB', name: 'Cuba', dialCode: '+53', slug: 'cuba' },
  { countryCode: 'CY', iso3: 'CYP', name: 'Cyprus', dialCode: '+357', slug: 'cyprus' },
  { countryCode: 'CZ', iso3: 'CZE', name: 'Czechia', dialCode: '+420', slug: 'czechia' },

  { countryCode: 'DK', iso3: 'DNK', name: 'Denmark', dialCode: '+45', slug: 'denmark' },
  { countryCode: 'DJ', iso3: 'DJI', name: 'Djibouti', dialCode: '+253', slug: 'djibouti' },
  { countryCode: 'DM', iso3: 'DMA', name: 'Dominica', dialCode: '+1-767', slug: 'dominica' },
  { countryCode: 'DO', iso3: 'DOM', name: 'Dominican Republic', dialCode: '+1-809', slug: 'dominican-republic' },

  { countryCode: 'EC', iso3: 'ECU', name: 'Ecuador', dialCode: '+593', slug: 'ecuador' },
  { countryCode: 'EG', iso3: 'EGY', name: 'Egypt', dialCode: '+20', slug: 'egypt' },
  { countryCode: 'SV', iso3: 'SLV', name: 'El Salvador', dialCode: '+503', slug: 'el-salvador' },
  { countryCode: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea', dialCode: '+240', slug: 'equatorial-guinea' },
  { countryCode: 'ER', iso3: 'ERI', name: 'Eritrea', dialCode: '+291', slug: 'eritrea' },
  { countryCode: 'EE', iso3: 'EST', name: 'Estonia', dialCode: '+372', slug: 'estonia' },
  { countryCode: 'SZ', iso3: 'SWZ', name: 'Eswatini', dialCode: '+268', slug: 'eswatini' },
  { countryCode: 'ET', iso3: 'ETH', name: 'Ethiopia', dialCode: '+251', slug: 'ethiopia' },

  { countryCode: 'FJ', iso3: 'FJI', name: 'Fiji', dialCode: '+679', slug: 'fiji' },
  { countryCode: 'FI', iso3: 'FIN', name: 'Finland', dialCode: '+358', slug: 'finland' },
  { countryCode: 'FR', iso3: 'FRA', name: 'France', dialCode: '+33', slug: 'france' },

  { countryCode: 'GA', iso3: 'GAB', name: 'Gabon', dialCode: '+241', slug: 'gabon' },
  { countryCode: 'GM', iso3: 'GMB', name: 'Gambia', dialCode: '+220', slug: 'gambia' },
  { countryCode: 'GE', iso3: 'GEO', name: 'Georgia', dialCode: '+995', slug: 'georgia' },
  { countryCode: 'DE', iso3: 'DEU', name: 'Germany', dialCode: '+49', slug: 'germany' },
  { countryCode: 'GH', iso3: 'GHA', name: 'Ghana', dialCode: '+233', slug: 'ghana' },
  { countryCode: 'GR', iso3: 'GRC', name: 'Greece', dialCode: '+30', slug: 'greece' },
  { countryCode: 'GD', iso3: 'GRD', name: 'Grenada', dialCode: '+1-473', slug: 'grenada' },
  { countryCode: 'GT', iso3: 'GTM', name: 'Guatemala', dialCode: '+502', slug: 'guatemala' },
  { countryCode: 'GN', iso3: 'GIN', name: 'Guinea', dialCode: '+224', slug: 'guinea' },
  { countryCode: 'GW', iso3: 'GNB', name: 'Guinea-Bissau', dialCode: '+245', slug: 'guinea-bissau' },
  { countryCode: 'GY', iso3: 'GUY', name: 'Guyana', dialCode: '+592', slug: 'guyana' },

  { countryCode: 'HT', iso3: 'HTI', name: 'Haiti', dialCode: '+509', slug: 'haiti' },
  { countryCode: 'HN', iso3: 'HND', name: 'Honduras', dialCode: '+504', slug: 'honduras' },
  { countryCode: 'HU', iso3: 'HUN', name: 'Hungary', dialCode: '+36', slug: 'hungary' },

  { countryCode: 'IS', iso3: 'ISL', name: 'Iceland', dialCode: '+354', slug: 'iceland' },
  { countryCode: 'IN', iso3: 'IND', name: 'India', dialCode: '+91', slug: 'india' },
  { countryCode: 'ID', iso3: 'IDN', name: 'Indonesia', dialCode: '+62', slug: 'indonesia' },
  { countryCode: 'IR', iso3: 'IRN', name: 'Iran', dialCode: '+98', slug: 'iran' },
  { countryCode: 'IQ', iso3: 'IRQ', name: 'Iraq', dialCode: '+964', slug: 'iraq' },
  { countryCode: 'IE', iso3: 'IRL', name: 'Ireland', dialCode: '+353', slug: 'ireland' },
  { countryCode: 'IL', iso3: 'ISR', name: 'Israel', dialCode: '+972', slug: 'israel' },
  { countryCode: 'IT', iso3: 'ITA', name: 'Italy', dialCode: '+39', slug: 'italy' },

  { countryCode: 'JM', iso3: 'JAM', name: 'Jamaica', dialCode: '+1-876', slug: 'jamaica' },
  { countryCode: 'JP', iso3: 'JPN', name: 'Japan', dialCode: '+81', slug: 'japan' },
  { countryCode: 'JO', iso3: 'JOR', name: 'Jordan', dialCode: '+962', slug: 'jordan' },

  { countryCode: 'KZ', iso3: 'KAZ', name: 'Kazakhstan', dialCode: '+7', slug: 'kazakhstan' },
  { countryCode: 'KE', iso3: 'KEN', name: 'Kenya', dialCode: '+254', slug: 'kenya' },
  { countryCode: 'KI', iso3: 'KIR', name: 'Kiribati', dialCode: '+686', slug: 'kiribati' },
  { countryCode: 'KW', iso3: 'KWT', name: 'Kuwait', dialCode: '+965', slug: 'kuwait' },
  { countryCode: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan', dialCode: '+996', slug: 'kyrgyzstan' },

  { countryCode: 'LA', iso3: 'LAO', name: 'Laos', dialCode: '+856', slug: 'laos' },
  { countryCode: 'LV', iso3: 'LVA', name: 'Latvia', dialCode: '+371', slug: 'latvia' },
  { countryCode: 'LB', iso3: 'LBN', name: 'Lebanon', dialCode: '+961', slug: 'lebanon' },
  { countryCode: 'LS', iso3: 'LSO', name: 'Lesotho', dialCode: '+266', slug: 'lesotho' },
  { countryCode: 'LR', iso3: 'LBR', name: 'Liberia', dialCode: '+231', slug: 'liberia' },
  { countryCode: 'LY', iso3: 'LBY', name: 'Libya', dialCode: '+218', slug: 'libya' },
  { countryCode: 'LI', iso3: 'LIE', name: 'Liechtenstein', dialCode: '+423', slug: 'liechtenstein' },
  { countryCode: 'LT', iso3: 'LTU', name: 'Lithuania', dialCode: '+370', slug: 'lithuania' },
  { countryCode: 'LU', iso3: 'LUX', name: 'Luxembourg', dialCode: '+352', slug: 'luxembourg' },

  { countryCode: 'MG', iso3: 'MDG', name: 'Madagascar', dialCode: '+261', slug: 'madagascar' },
  { countryCode: 'MW', iso3: 'MWI', name: 'Malawi', dialCode: '+265', slug: 'malawi' },
  { countryCode: 'MY', iso3: 'MYS', name: 'Malaysia', dialCode: '+60', slug: 'malaysia' },
  { countryCode: 'MV', iso3: 'MDV', name: 'Maldives', dialCode: '+960', slug: 'maldives' },
  { countryCode: 'ML', iso3: 'MLI', name: 'Mali', dialCode: '+223', slug: 'mali' },
  { countryCode: 'MT', iso3: 'MLT', name: 'Malta', dialCode: '+356', slug: 'malta' },
  { countryCode: 'MH', iso3: 'MHL', name: 'Marshall Islands', dialCode: '+692', slug: 'marshall-islands' },
  { countryCode: 'MR', iso3: 'MRT', name: 'Mauritania', dialCode: '+222', slug: 'mauritania' },
  { countryCode: 'MU', iso3: 'MUS', name: 'Mauritius', dialCode: '+230', slug: 'mauritius' },
  { countryCode: 'MX', iso3: 'MEX', name: 'Mexico', dialCode: '+52', slug: 'mexico' },
  { countryCode: 'FM', iso3: 'FSM', name: 'Micronesia', dialCode: '+691', slug: 'micronesia' },
  { countryCode: 'MD', iso3: 'MDA', name: 'Moldova', dialCode: '+373', slug: 'moldova' },
  { countryCode: 'MC', iso3: 'MCO', name: 'Monaco', dialCode: '+377', slug: 'monaco' },
  { countryCode: 'MN', iso3: 'MNG', name: 'Mongolia', dialCode: '+976', slug: 'mongolia' },
  { countryCode: 'ME', iso3: 'MNE', name: 'Montenegro', dialCode: '+382', slug: 'montenegro' },
  { countryCode: 'MA', iso3: 'MAR', name: 'Morocco', dialCode: '+212', slug: 'morocco' },
  { countryCode: 'MZ', iso3: 'MOZ', name: 'Mozambique', dialCode: '+258', slug: 'mozambique' },
  { countryCode: 'MM', iso3: 'MMR', name: 'Myanmar', dialCode: '+95', slug: 'myanmar' },

  { countryCode: 'NA', iso3: 'NAM', name: 'Namibia', dialCode: '+264', slug: 'namibia' },
  { countryCode: 'NR', iso3: 'NRU', name: 'Nauru', dialCode: '+674', slug: 'nauru' },
  { countryCode: 'NP', iso3: 'NPL', name: 'Nepal', dialCode: '+977', slug: 'nepal' },
  { countryCode: 'NL', iso3: 'NLD', name: 'Netherlands', dialCode: '+31', slug: 'netherlands' },
  { countryCode: 'NZ', iso3: 'NZL', name: 'New Zealand', dialCode: '+64', slug: 'new-zealand' },
  { countryCode: 'NI', iso3: 'NIC', name: 'Nicaragua', dialCode: '+505', slug: 'nicaragua' },
  { countryCode: 'NE', iso3: 'NER', name: 'Niger', dialCode: '+227', slug: 'niger' },
  { countryCode: 'NG', iso3: 'NGA', name: 'Nigeria', dialCode: '+234', slug: 'nigeria' },
  { countryCode: 'KP', iso3: 'PRK', name: 'North Korea', dialCode: '+850', slug: 'north-korea' },
  { countryCode: 'MK', iso3: 'MKD', name: 'North Macedonia', dialCode: '+389', slug: 'north-macedonia' },
  { countryCode: 'NO', iso3: 'NOR', name: 'Norway', dialCode: '+47', slug: 'norway' },

  { countryCode: 'OM', iso3: 'OMN', name: 'Oman', dialCode: '+968', slug: 'oman' },

  { countryCode: 'PK', iso3: 'PAK', name: 'Pakistan', dialCode: '+92', slug: 'pakistan' },
  { countryCode: 'PW', iso3: 'PLW', name: 'Palau', dialCode: '+680', slug: 'palau' },
  { countryCode: 'PS', iso3: 'PSE', name: 'Palestine', dialCode: '+970', slug: 'palestine' },
  { countryCode: 'PA', iso3: 'PAN', name: 'Panama', dialCode: '+507', slug: 'panama' },
  { countryCode: 'PG', iso3: 'PNG', name: 'Papua New Guinea', dialCode: '+675', slug: 'papua-new-guinea' },
  { countryCode: 'PY', iso3: 'PRY', name: 'Paraguay', dialCode: '+595', slug: 'paraguay' },
  { countryCode: 'PE', iso3: 'PER', name: 'Peru', dialCode: '+51', slug: 'peru' },
  { countryCode: 'PH', iso3: 'PHL', name: 'Philippines', dialCode: '+63', slug: 'philippines' },
  { countryCode: 'PL', iso3: 'POL', name: 'Poland', dialCode: '+48', slug: 'poland' },
  { countryCode: 'PT', iso3: 'PRT', name: 'Portugal', dialCode: '+351', slug: 'portugal' },

  { countryCode: 'QA', iso3: 'QAT', name: 'Qatar', dialCode: '+974', slug: 'qatar' },

  { countryCode: 'RO', iso3: 'ROU', name: 'Romania', dialCode: '+40', slug: 'romania' },
  { countryCode: 'RU', iso3: 'RUS', name: 'Russia', dialCode: '+7', slug: 'russia' },
  { countryCode: 'RW', iso3: 'RWA', name: 'Rwanda', dialCode: '+250', slug: 'rwanda' },

  { countryCode: 'KN', iso3: 'KNA', name: 'Saint Kitts and Nevis', dialCode: '+1-869', slug: 'saint-kitts-and-nevis' },
  { countryCode: 'LC', iso3: 'LCA', name: 'Saint Lucia', dialCode: '+1-758', slug: 'saint-lucia' },
  { countryCode: 'VC', iso3: 'VCT', name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', slug: 'saint-vincent-and-the-grenadines' },
  { countryCode: 'WS', iso3: 'WSM', name: 'Samoa', dialCode: '+685', slug: 'samoa' },
  { countryCode: 'SM', iso3: 'SMR', name: 'San Marino', dialCode: '+378', slug: 'san-marino' },
  { countryCode: 'ST', iso3: 'STP', name: 'São Tomé and Príncipe', dialCode: '+239', slug: 'sao-tome-and-principe' },
  { countryCode: 'SA', iso3: 'SAU', name: 'Saudi Arabia', dialCode: '+966', slug: 'saudi-arabia' },
  { countryCode: 'SN', iso3: 'SEN', name: 'Senegal', dialCode: '+221', slug: 'senegal' },
  { countryCode: 'RS', iso3: 'SRB', name: 'Serbia', dialCode: '+381', slug: 'serbia' },
  { countryCode: 'SC', iso3: 'SYC', name: 'Seychelles', dialCode: '+248', slug: 'seychelles' },
  { countryCode: 'SL', iso3: 'SLE', name: 'Sierra Leone', dialCode: '+232', slug: 'sierra-leone' },
  { countryCode: 'SG', iso3: 'SGP', name: 'Singapore', dialCode: '+65', slug: 'singapore' },
  { countryCode: 'SK', iso3: 'SVK', name: 'Slovakia', dialCode: '+421', slug: 'slovakia' },
  { countryCode: 'SI', iso3: 'SVN', name: 'Slovenia', dialCode: '+386', slug: 'slovenia' },
  { countryCode: 'SB', iso3: 'SLB', name: 'Solomon Islands', dialCode: '+677', slug: 'solomon-islands' },
  { countryCode: 'SO', iso3: 'SOM', name: 'Somalia', dialCode: '+252', slug: 'somalia' },
  { countryCode: 'ZA', iso3: 'ZAF', name: 'South Africa', dialCode: '+27', slug: 'south-africa' },
  { countryCode: 'KR', iso3: 'KOR', name: 'South Korea', dialCode: '+82', slug: 'south-korea' },
  { countryCode: 'SS', iso3: 'SSD', name: 'South Sudan', dialCode: '+211', slug: 'south-sudan' },
  { countryCode: 'ES', iso3: 'ESP', name: 'Spain', dialCode: '+34', slug: 'spain' },
  { countryCode: 'LK', iso3: 'LKA', name: 'Sri Lanka', dialCode: '+94', slug: 'sri-lanka' },
  { countryCode: 'SD', iso3: 'SDN', name: 'Sudan', dialCode: '+249', slug: 'sudan' },
  { countryCode: 'SR', iso3: 'SUR', name: 'Suriname', dialCode: '+597', slug: 'suriname' },
  { countryCode: 'SE', iso3: 'SWE', name: 'Sweden', dialCode: '+46', slug: 'sweden' },
  { countryCode: 'CH', iso3: 'CHE', name: 'Switzerland', dialCode: '+41', slug: 'switzerland' },
  { countryCode: 'SY', iso3: 'SYR', name: 'Syria', dialCode: '+963', slug: 'syria' },

  { countryCode: 'TW', iso3: 'TWN', name: 'Taiwan', dialCode: '+886', slug: 'taiwan' },
  { countryCode: 'TJ', iso3: 'TJK', name: 'Tajikistan', dialCode: '+992', slug: 'tajikistan' },
  { countryCode: 'TZ', iso3: 'TZA', name: 'Tanzania', dialCode: '+255', slug: 'tanzania' },
  { countryCode: 'TH', iso3: 'THA', name: 'Thailand', dialCode: '+66', slug: 'thailand' },
  { countryCode: 'TL', iso3: 'TLS', name: 'Timor-Leste', dialCode: '+670', slug: 'timor-leste' },
  { countryCode: 'TG', iso3: 'TGO', name: 'Togo', dialCode: '+228', slug: 'togo' },
  { countryCode: 'TO', iso3: 'TON', name: 'Tonga', dialCode: '+676', slug: 'tonga' },
  { countryCode: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago', dialCode: '+1-868', slug: 'trinidad-and-tobago' },
  { countryCode: 'TN', iso3: 'TUN', name: 'Tunisia', dialCode: '+216', slug: 'tunisia' },
  { countryCode: 'TR', iso3: 'TUR', name: 'Turkey', dialCode: '+90', slug: 'turkey' },
  { countryCode: 'TM', iso3: 'TKM', name: 'Turkmenistan', dialCode: '+993', slug: 'turkmenistan' },
  { countryCode: 'TV', iso3: 'TUV', name: 'Tuvalu', dialCode: '+688', slug: 'tuvalu' },

  { countryCode: 'UG', iso3: 'UGA', name: 'Uganda', dialCode: '+256', slug: 'uganda' },
  { countryCode: 'UA', iso3: 'UKR', name: 'Ukraine', dialCode: '+380', slug: 'ukraine' },
  { countryCode: 'AE', iso3: 'ARE', name: 'United Arab Emirates', dialCode: '+971', slug: 'united-arab-emirates' },
  { countryCode: 'GB', iso3: 'GBR', name: 'United Kingdom', dialCode: '+44', slug: 'united-kingdom' },
  { countryCode: 'US', iso3: 'USA', name: 'United States', dialCode: '+1', slug: 'united-states' },
  { countryCode: 'UY', iso3: 'URY', name: 'Uruguay', dialCode: '+598', slug: 'uruguay' },
  { countryCode: 'UZ', iso3: 'UZB', name: 'Uzbekistan', dialCode: '+998', slug: 'uzbekistan' },

  { countryCode: 'VU', iso3: 'VUT', name: 'Vanuatu', dialCode: '+678', slug: 'vanuatu' },
  { countryCode: 'VA', iso3: 'VAT', name: 'Vatican City', dialCode: '+39', slug: 'vatican-city' },
  { countryCode: 'VE', iso3: 'VEN', name: 'Venezuela', dialCode: '+58', slug: 'venezuela' },
  { countryCode: 'VN', iso3: 'VNM', name: 'Vietnam', dialCode: '+84', slug: 'vietnam' },

  { countryCode: 'YE', iso3: 'YEM', name: 'Yemen', dialCode: '+967', slug: 'yemen' },

  { countryCode: 'ZM', iso3: 'ZMB', name: 'Zambia', dialCode: '+260', slug: 'zambia' },
  { countryCode: 'ZW', iso3: 'ZWE', name: 'Zimbabwe', dialCode: '+263', slug: 'zimbabwe' }
];

async function seedMasterData() {
  console.log('🌱 Seeding Master Data...');

  // --------------------------------------------------------
  // CONTINENTS
  // --------------------------------------------------------
  if (typeof CONTINENTS !== 'undefined' && CONTINENTS.length > 0) {
    console.log('Seeding Continents...');
    await prisma.continent.createMany({
      data: CONTINENTS.map(item => ({
        code: item.code,
        name: item.name,
        slug: item.slug
      })),
      skipDuplicates: true
    });
  }

  // --------------------------------------------------------
  // CURRENCIES
  // --------------------------------------------------------
  if (typeof CURRENCIES !== 'undefined' && CURRENCIES.length > 0) {
    console.log('Seeding Currencies...');
    let i = 1;
    await prisma.currency.createMany({
      data: CURRENCIES.map(item => ({
        code: item.code,
        numericCode: i++,
        name: item.name,
        symbol: item.symbol
      })),
      skipDuplicates: true
    });
  }

  // --------------------------------------------------------
  // LANGUAGES
  // --------------------------------------------------------
  if (typeof LANGUAGES !== 'undefined' && LANGUAGES.length > 0) {
    console.log('Seeding Languages...');
    await prisma.language.createMany({
      data: LANGUAGES.map(item => ({
        code: item.code,
        locale: item.locale || item.code,
        name: item.name
      })),
      skipDuplicates: true
    });
  }

  // --------------------------------------------------------
  // COUNTRIES
  // --------------------------------------------------------
  if (typeof COUNTRIES !== 'undefined' && COUNTRIES.length > 0) {
    console.log('Seeding Countries...');
    const continents = await prisma.continent.findMany();
    const contMap = {};
    for (const c of continents) {
      contMap[c.code] = c.id;
    }
    const defaultContinent = continents[0];

    if (defaultContinent) {
      await prisma.country.createMany({
        data: COUNTRIES.map(item => ({
          iso2: item.iso2 || item.countryCode || item.code,
          iso3: item.iso3 || item.iso2 || item.countryCode || item.code,
          numericCode: item.numericCode ? parseInt(item.numericCode, 10) : 0,
          name: item.name,
          phoneCode: item.phoneCode || item.dialCode || '',
          slug: item.slug || (item.name.toLowerCase().replace(/\s+/g, '-')),
          continentId: contMap[item.continentCode] || defaultContinent.id
        })),
        skipDuplicates: true
      });
    }
  }

  // --------------------------------------------------------
  // INDIA STATES
  // --------------------------------------------------------
  if (typeof INDIA_STATES !== 'undefined' && INDIA_STATES.length > 0) {
    console.log('Seeding India States...');
    const india = await prisma.country.findFirst({ where: { iso2: 'IN' } });
    if (india) {
      await prisma.state.createMany({
        data: INDIA_STATES.map(item => ({
          countryId: india.id,
          code: item.code,
          name: item.name,
          slug: item.slug || (item.name.toLowerCase().replace(/\s+/g, '-'))
        })),
        skipDuplicates: true
      });
    }
  }

  // --------------------------------------------------------
  // INDIA CITIES
  // --------------------------------------------------------
  if (typeof INDIA_CITIES !== 'undefined' && Object.keys(INDIA_CITIES).length > 0) {
    console.log('Seeding India Cities...');
    const india = await prisma.country.findFirst({ where: { iso2: 'IN' } });
    if (india) {
      const states = await prisma.state.findMany({ where: { countryId: india.id } });
      const stateMap = {};
      for (const s of states) { stateMap[s.code] = s.id; }

      const cityData = [];
      for (const [stateCode, cities] of Object.entries(INDIA_CITIES)) {
        const stateId = stateMap[stateCode];
        if (stateId) {
          for (const cityName of cities) {
            cityData.push({
              countryId: india.id,
              stateId: stateId,
              name: cityName,
              slug: cityName.toLowerCase().replace(/\s+/g, '-')
            });
          }
        }
      }
      if (cityData.length > 0) {
        await prisma.city.createMany({
          data: cityData,
          skipDuplicates: true
        });
      }
    }
  }

  // --------------------------------------------------------
  // PHONE COUNTRY CODES
  // --------------------------------------------------------
  if (typeof PHONE_COUNTRY_CODES !== 'undefined' && PHONE_COUNTRY_CODES.length > 0) {
    console.log('Seeding Phone Country Codes...');
    const countries = await prisma.country.findMany();
    const countryMap = {};
    for (const c of countries) {
      countryMap[c.iso2] = c.id;
    }

    await prisma.phoneCountryCode.createMany({
      data: PHONE_COUNTRY_CODES.map(item => ({
        countryId: countryMap[item.iso2 || item.countryCode] || null,
        iso2: item.iso2 || item.countryCode,
        name: item.name,
        dialCode: item.dialCode,
        flag: item.flag || ''
      })),
      skipDuplicates: true
    });
  }

  console.log('✅ Master Data Seeded Successfully!');
}

seedMasterData()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
